## Welcome to Eunoia - Shining light on your well-being.

#About
Eunoia is designed to help young adults detect early signs of mental discomfort before situations escalate. Instead of waiting days or weeks for appointments, Eunoia provides quick, approachable check-ins to encourage awareness and timely support, also act as a friend who never judges. It is followed by giving motivational quotes to keep going even if the times are hard. It avoids providing hallucinated answers to use queries and suggest them to refer to a practitioner if a situation like this arise.

#Requirements
- python3.9
- install all packages in 'requirement.txt' using pip install -r requirements.txt

#Data
All dataset files are located in the 'data' folder from blackbox, headspace, beyondblue and lifeline. 

"Collections.csv" is paragraphs containing information about the diseases with the official sites/pdf they were extracted from. 

"Questions.csv" contains around 4-5 questions for each disease and are answered using the "collections.csv"'s information. To ensure the answers are not vague, uses the updated data. 

Both the files were linked using the disease name column from each file.

#Source Code
This contains all the source codes necessary for data generation, indexing, retrieving, searching using Ollama- Nomic-embbed-text for embeddings and mistral:latest for reterival and generation

#Target
The 'target' directory includes all the output generated by the source codes for the RAG model using Ollama.