conditions:
  - disease: "Depression"
    help_url: "https://www.blackdoginstitute.org.au/resources-support/depression/"
    pdfs:
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/Causes-of-depression.pdf"
        label: "causes"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/Symptoms-of-depression.pdf"
        label: "symptoms"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/Treatments-for-depression.pdf"
        label: "treatment"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/Depression-in-adolescents.pdf"
        label: "facts"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/Exercise-and-depression.pdf"
        label: "other"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/Managing-depression-with-exercise.pdf"
        label: "other"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/eMental-health.pdf"
        label: "other"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2023/01/Managing-your-mental-health-with-ehealth.pdf"
        label: "other"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/St-Johns-Worts-treatment.pdf"
        label: "other"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/Depression-during-pregnancy.pdf"
        label: "other"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/The-management-of-antenatal-and-postnatal-depression.pdf"
        label: "other"

  - disease: "Anxiety"
    help_url: "https://www.blackdoginstitute.org.au/resources-support/anxiety/"
    pdfs:
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/Signs-and-Symptoms-of-Anxiety-fact-sheet.pdf"
        label: "symptoms"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/Seeking-help-for-anxiety-fact-sheet.pdf"
        label: "treatment"

  - disease: "Stress"
    help_url: "https://www.blackdoginstitute.org.au/resources-support/stress/"
    pdfs:
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/Stress-and-its-impact-on-you-fact-sheet.pdf"
        label: "facts"

  - disease: "Bipolar Disorder"
    help_url: "https://www.blackdoginstitute.org.au/resources-support/bipolar-disorder/"
    pdfs:
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/Causes-of-bipolar-disorder.pdf"
        label: "causes"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2024/04/Bipolar-disorder-symptoms-fact-sheet.pdf"
        label: "symptoms"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/Treatments-for-bipolar-disorder-fact-sheet.pdf"
        label: "treatment"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/Staying-on-course-with-treatment-fact-sheet.pdf"
        label: "other"
      - url: "https://www.blackdoginstitute.org.au/wp-content/uploads/2022/06/Bipolar-disorder-in-young-people-fact-sheet.pdf"
